### ISSUE TITLE
Add progress indicator while AI is thinking

### ISSUE THREAD

**Issue by KarelPeeters** [henrykvdb/UltimateTTTAndroid#3]
Sometimes the AI gets "stuck" for while, and it takes quite a bit of time for the AI to come up with a move. Would it possible to add a progress indicator of some sort?

**Comment by Damzwan** [comment]
Any progress on this issue yet?

**Comment by henrykvdb** [comment]
This issue is currently not being worked on so feel free to open a pull request.

**Comment by henrykvdb** [comment]
The feature is now added (although not really needed anymore since the bot plays instant now)
